// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_8 = "CgkI0ryr_eIQEAIQCQ"; // <GPGSID>
        public const string leaderboard_landing_king = "CgkI0ryr_eIQEAIQAQ"; // <GPGSID>
        public const string achievement = "CgkI0ryr_eIQEAIQAg"; // <GPGSID>
        public const string achievement_2 = "CgkI0ryr_eIQEAIQAw"; // <GPGSID>
        public const string achievement_3 = "CgkI0ryr_eIQEAIQBA"; // <GPGSID>
        public const string achievement____ = "CgkI0ryr_eIQEAIQCg"; // <GPGSID>
        public const string achievement_6 = "CgkI0ryr_eIQEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkI0ryr_eIQEAIQCA"; // <GPGSID>
        public const string achievement_4 = "CgkI0ryr_eIQEAIQBQ"; // <GPGSID>
        public const string achievement_5 = "CgkI0ryr_eIQEAIQBg"; // <GPGSID>

}

